export const MEDICAL_CASE_STATUSES = [
  'NEW_LEAD',
  'REGISTERED',
  'WAITING_FOR_DOCUMENTS',
  'DOCUMENTS_UPLOADED',
  'UNDER_REVIEW',
  'DOCTOR_ASSIGNED',
  'WAITING_PATIENT_CONFIRMATION',
  'WAITING_PAYMENT',
  'CONSULTATION_BOOKED',
  'CONSULTATION_COMPLETED',
  'LOCAL_TREATMENT',
  'TREATMENT_IN_KAZAKHSTAN',
  'TRAVEL_PREPARATION',
  'ARRIVED_TO_KAZAKHSTAN',
  'IN_TREATMENT',
  'RECOVERY',
  'COMPLETED',
  'CANCELLED',
]

export const LEGACY_MEDICAL_CASE_STATUS_MAP = {
  NEW: 'NEW_LEAD',
  DOCS_PENDING: 'WAITING_FOR_DOCUMENTS',
  ASSIGNED: 'UNDER_REVIEW',
  IN_REVIEW: 'UNDER_REVIEW',
  MATCHING: 'DOCTOR_ASSIGNED',
  CONSULTATION_SCHEDULED: 'CONSULTATION_BOOKED',
  PLAN_FORMING: 'CONSULTATION_COMPLETED',
  PLAN_READY: 'WAITING_PATIENT_CONFIRMATION',
  PATIENT_DECISION: 'WAITING_PATIENT_CONFIRMATION',
  CONFIRMED: 'TREATMENT_IN_KAZAKHSTAN',
  VISA_PROCESS: 'TRAVEL_PREPARATION',
  TRAVEL_ARRANGED: 'TRAVEL_PREPARATION',
  ARRIVED: 'ARRIVED_TO_KAZAKHSTAN',
  DISCHARGED: 'RECOVERY',
  POST_CARE: 'RECOVERY',
  NO_TREATMENT_NEEDED: 'LOCAL_TREATMENT',
}

export const STATUS_VARIANTS = {
  NEW_LEAD: 'info',
  REGISTERED: 'info',
  WAITING_FOR_DOCUMENTS: 'warning',
  DOCUMENTS_UPLOADED: 'primary',
  UNDER_REVIEW: 'primary',
  DOCTOR_ASSIGNED: 'secondary',
  WAITING_PATIENT_CONFIRMATION: 'warning',
  WAITING_PAYMENT: 'warning',
  CONSULTATION_BOOKED: 'secondary',
  CONSULTATION_COMPLETED: 'secondary',
  LOCAL_TREATMENT: 'success',
  TREATMENT_IN_KAZAKHSTAN: 'success',
  TRAVEL_PREPARATION: 'warning',
  ARRIVED_TO_KAZAKHSTAN: 'primary',
  IN_TREATMENT: 'info',
  RECOVERY: 'secondary',
  COMPLETED: 'success',
  CANCELLED: 'danger',
}

export const MEDICAL_CASE_TRANSITIONS = {
  NEW_LEAD: ['REGISTERED', 'WAITING_FOR_DOCUMENTS', 'CANCELLED'],
  REGISTERED: ['WAITING_FOR_DOCUMENTS', 'CANCELLED'],
  WAITING_FOR_DOCUMENTS: ['DOCUMENTS_UPLOADED', 'UNDER_REVIEW', 'CANCELLED'],
  DOCUMENTS_UPLOADED: ['UNDER_REVIEW', 'WAITING_FOR_DOCUMENTS', 'CANCELLED'],
  UNDER_REVIEW: ['WAITING_FOR_DOCUMENTS', 'DOCTOR_ASSIGNED', 'LOCAL_TREATMENT', 'CANCELLED'],
  DOCTOR_ASSIGNED: ['WAITING_PATIENT_CONFIRMATION', 'WAITING_FOR_DOCUMENTS', 'CANCELLED'],
  WAITING_PATIENT_CONFIRMATION: ['WAITING_PAYMENT', 'DOCTOR_ASSIGNED', 'CANCELLED'],
  WAITING_PAYMENT: ['CONSULTATION_BOOKED', 'WAITING_PATIENT_CONFIRMATION', 'CANCELLED'],
  CONSULTATION_BOOKED: ['CONSULTATION_COMPLETED', 'WAITING_PATIENT_CONFIRMATION', 'CANCELLED'],
  CONSULTATION_COMPLETED: ['LOCAL_TREATMENT', 'TREATMENT_IN_KAZAKHSTAN', 'WAITING_FOR_DOCUMENTS', 'CANCELLED'],
  LOCAL_TREATMENT: ['COMPLETED', 'CANCELLED'],
  TREATMENT_IN_KAZAKHSTAN: ['TRAVEL_PREPARATION', 'CANCELLED'],
  TRAVEL_PREPARATION: ['ARRIVED_TO_KAZAKHSTAN', 'CANCELLED'],
  ARRIVED_TO_KAZAKHSTAN: ['IN_TREATMENT', 'CANCELLED'],
  IN_TREATMENT: ['RECOVERY', 'CANCELLED'],
  RECOVERY: ['COMPLETED', 'CANCELLED'],
  COMPLETED: [],
  CANCELLED: [],
}

export const ROLE_STATUS_TRANSITIONS = {
  patient: ['REGISTERED', 'WAITING_FOR_DOCUMENTS', 'DOCUMENTS_UPLOADED', 'WAITING_PAYMENT', 'CANCELLED'],
  doctor: ['WAITING_FOR_DOCUMENTS', 'CONSULTATION_COMPLETED', 'LOCAL_TREATMENT', 'TREATMENT_IN_KAZAKHSTAN'],
  manager: [
    'REGISTERED',
    'WAITING_FOR_DOCUMENTS',
    'DOCUMENTS_UPLOADED',
    'UNDER_REVIEW',
    'DOCTOR_ASSIGNED',
    'WAITING_PATIENT_CONFIRMATION',
    'WAITING_PAYMENT',
    'CONSULTATION_BOOKED',
    'CONSULTATION_COMPLETED',
    'LOCAL_TREATMENT',
    'TREATMENT_IN_KAZAKHSTAN',
    'TRAVEL_PREPARATION',
    'ARRIVED_TO_KAZAKHSTAN',
    'IN_TREATMENT',
    'RECOVERY',
    'COMPLETED',
    'CANCELLED',
  ],
  coordinator: [
    'WAITING_FOR_DOCUMENTS',
    'DOCUMENTS_UPLOADED',
    'UNDER_REVIEW',
    'DOCTOR_ASSIGNED',
    'WAITING_PATIENT_CONFIRMATION',
    'CONSULTATION_BOOKED',
    'CONSULTATION_COMPLETED',
    'LOCAL_TREATMENT',
    'TREATMENT_IN_KAZAKHSTAN',
    'CANCELLED',
  ],
  admin: MEDICAL_CASE_STATUSES,
}

export const CASE_SLA_HOURS = {
  NEW_LEAD: 2,
  REGISTERED: 4,
  WAITING_FOR_DOCUMENTS: 48,
  DOCUMENTS_UPLOADED: 4,
  UNDER_REVIEW: 24,
  DOCTOR_ASSIGNED: 24,
  WAITING_PATIENT_CONFIRMATION: 72,
  WAITING_PAYMENT: 1,
  CONSULTATION_BOOKED: 72,
  CONSULTATION_COMPLETED: 12,
  LOCAL_TREATMENT: 24,
  TREATMENT_IN_KAZAKHSTAN: 24,
  TRAVEL_PREPARATION: 72,
  ARRIVED_TO_KAZAKHSTAN: 8,
  IN_TREATMENT: 24,
  RECOVERY: 168,
}

export const TERMINAL_CASE_STATUSES = ['COMPLETED', 'CANCELLED']

export function normalizeCaseStatus(status) {
  if (!status) return 'NEW_LEAD'
  if (MEDICAL_CASE_STATUSES.includes(status)) return status
  return LEGACY_MEDICAL_CASE_STATUS_MAP[status] || status
}

export function formatCaseStatus(status, t) {
  const key = normalizeCaseStatus(status) || 'NEW_LEAD'
  if (t) {
    const translated = t(`case_status.${key}`, { defaultValue: '' })
    if (translated) return translated
  }
  return String(key)
    .split('_')
    .map(word => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
    .join(' ')
}

export function getAllowedCaseTransitions(role, fromStatus) {
  const normalizedFrom = normalizeCaseStatus(fromStatus)
  const allowedTargets = ROLE_STATUS_TRANSITIONS[role || 'patient'] || []
  return (MEDICAL_CASE_TRANSITIONS[normalizedFrom] || []).filter(status => allowedTargets.includes(status))
}

export function getCaseSla(caseItem, now = new Date()) {
  const status = normalizeCaseStatus(caseItem?.status)
  const hours = CASE_SLA_HOURS[status]
  if (!hours || TERMINAL_CASE_STATUSES.includes(status)) {
    return { hours, overdue: false, remainingHours: null }
  }

  const start = new Date(caseItem?.updatedAt || caseItem?.createdAt || now)
  const due = new Date(start.getTime() + hours * 60 * 60 * 1000)
  const remainingHours = Math.ceil((due.getTime() - now.getTime()) / (60 * 60 * 1000))

  return {
    hours,
    due,
    overdue: remainingHours <= 0,
    remainingHours,
  }
}
